"""Criação das tabelas iniciais

Revision ID: 19b27422e62b
Revises: 
Create Date: 2025-04-23 16:00:10.829891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b27422e62b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impressoras',
    sa.Column('Serie', sa.String(length=50), nullable=False),
    sa.Column('Modelo', sa.String(length=50), nullable=False),
    sa.Column('Contrato', sa.String(length=4), nullable=False),
    sa.Column('Secretaria', sa.String(length=10), nullable=False),
    sa.Column('Localizacao', sa.String(length=50), nullable=False),
    sa.Column('IP', sa.String(length=50), nullable=False),
    sa.Column('Tipo', sa.String(length=15), nullable=False),
    sa.Column('Data_de_criacao', sa.DateTime(timezone=6), nullable=False),
    sa.Column('Ultimo_update', sa.DateTime(timezone=6), nullable=False),
    sa.PrimaryKeyConstraint('Serie'),
    sa.UniqueConstraint('IP')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bilhetagem',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Serie', sa.String(length=50), nullable=False),
    sa.Column('Contrato', sa.String(length=50), nullable=False),
    sa.Column('Localizacao', sa.String(length=50), nullable=False),
    sa.Column('Tipo', sa.String(length=50), nullable=False),
    sa.Column('Ano', sa.String(length=50), nullable=False),
    sa.Column('Mes', sa.String(length=50), nullable=False),
    sa.Column('Bilhetagem', sa.Integer(), nullable=False),
    sa.Column('Data_de_criacao', sa.DateTime(timezone=6), nullable=False),
    sa.Column('Ultimo_update', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['Serie'], ['impressoras.Serie'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('chamados',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Título', sa.String(length=50), nullable=False),
    sa.Column('Localizacao', sa.String(length=50), nullable=False),
    sa.Column('Descricao', sa.String(length=2000), nullable=False),
    sa.Column('Serie_impressora', sa.String(length=50), nullable=False),
    sa.Column('Data_de_criacao', sa.DateTime(timezone=6), nullable=False),
    sa.Column('Ultimo_update', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['Serie_impressora'], ['impressoras.Serie'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(timezone=6), nullable=False),
    sa.Column('ultimo_update', sa.DateTime(timezone=6), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('chamados')
    op.drop_table('bilhetagem')
    op.drop_table('roles')
    op.drop_table('impressoras')
    # ### end Alembic commands ###
