"""Add default current_timestamp to ultimo_update column in all tables

Revision ID: 59c88cae44dc
Revises: 54d44bcd8fc2
Create Date: 2025-04-23 20:51:01.326952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c88cae44dc'
down_revision = '54d44bcd8fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['Serie'], ['Serie'])

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['Serie_impressora'], ['Serie'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
