"""Ampliação do campo descricao da role

Revision ID: 6ae7368e65b3
Revises: d32636bd7fbd
Create Date: 2025-04-23 09:08:34.103080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ae7368e65b3'
down_revision = 'd32636bd7fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['serie'], ['serie'])

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['impressora_id'], ['serie'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('Descricao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               type_=sa.String(length=250),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('Descricao',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               existing_nullable=False)

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
