"""Remoção do unique=true da chave impressoras.IP

Revision ID: 863b85176875
Revises: 19b27422e62b
Create Date: 2025-04-23 16:21:46.862408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863b85176875'
down_revision = '19b27422e62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['Serie'], ['Serie'])

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['Serie_impressora'], ['Serie'])

    with op.batch_alter_table('impressoras', schema=None) as batch_op:
        batch_op.drop_index('IP')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('impressoras', schema=None) as batch_op:
        batch_op.create_index('IP', ['IP'], unique=True)

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
