"""Alteração do nome Descricao para descricao na tabela role

Revision ID: b98c1fdb7a57
Revises: 6ae7368e65b3
Create Date: 2025-04-23 09:10:13.757689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98c1fdb7a57'
down_revision = '6ae7368e65b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['serie'], ['serie'])

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['impressora_id'], ['serie'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
