"""Criação das tabelas iniciais

Revision ID: d17d345a96bd
Revises: 
Create Date: 2025-04-16 14:06:16.998161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17d345a96bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impressoras',
    sa.Column('serie', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(timezone=6), nullable=False),
    sa.Column('ultimo_update', sa.DateTime(timezone=6), nullable=False),
    sa.PrimaryKeyConstraint('serie'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bilhetagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=50), nullable=False),
    sa.Column('contrato', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.String(length=50), nullable=False),
    sa.Column('mes', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(timezone=6), nullable=False),
    sa.Column('ultimo_update', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['serie'], ['impressoras.serie'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('impressora_id', sa.String(length=50), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(timezone=6), nullable=False),
    sa.Column('ultimo_update', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['impressora_id'], ['impressoras.serie'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(timezone=6), nullable=False),
    sa.Column('ultimo_update', sa.DateTime(timezone=6), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('chamados')
    op.drop_table('bilhetagem')
    op.drop_table('roles')
    op.drop_table('impressoras')
    # ### end Alembic commands ###
