"""Criação das tabelas iniciais

Revision ID: d32636bd7fbd
Revises: 
Create Date: 2025-04-23 09:05:15.801303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32636bd7fbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['serie'], ['serie'])

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impressoras', ['impressora_id'], ['serie'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bilhetagem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
